// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Account
    {
        public Account()
        {
            Depot = new HashSet<Depot>();
        }

        public int Aid { get; set; }
        public string Description { get; set; }
        public int? Uid { get; set; }

        public virtual Users UidNavigation { get; set; }
        public virtual ICollection<Depot> Depot { get; set; }
    }
}