// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Bonds
    {
        public Bonds()
        {
            DepotBonds = new HashSet<DepotBonds>();
        }

        public int Seid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Securitynumber { get; set; }
        public DateOnly? Runtime { get; set; }
        public decimal? Yield { get; set; }

        public virtual ICollection<DepotBonds> DepotBonds { get; set; }
    }
}