// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Depot
    {
        public Depot()
        {
            DepotBonds = new HashSet<DepotBonds>();
            DepotStocks = new HashSet<DepotStocks>();
        }

        public int Did { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int? Uid { get; set; }
        public int? Aid { get; set; }

        public virtual Account AidNavigation { get; set; }
        public virtual Users UidNavigation { get; set; }
        public virtual ICollection<DepotBonds> DepotBonds { get; set; }
        public virtual ICollection<DepotStocks> DepotStocks { get; set; }
    }
}