// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class DepotStocks
    {
        public DepotStocks()
        {
            Transactionlog = new HashSet<Transactionlog>();
        }

        public int? Did { get; set; }
        public int? Seid { get; set; }
        public int Sharenumber { get; set; }
        public decimal? Purcharsevalue { get; set; }

        public virtual Depot DidNavigation { get; set; }
        public virtual Stocks Se { get; set; }
        public virtual ICollection<Transactionlog> Transactionlog { get; set; }
    }
}