// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Stocks
    {
        public Stocks()
        {
            DepotStocks = new HashSet<DepotStocks>();
            Transactionlog = new HashSet<Transactionlog>();
        }

        public int Seid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Securitynumber { get; set; }
        public decimal? Stockvalue { get; set; }

        public virtual ICollection<DepotStocks> DepotStocks { get; set; }
        public virtual ICollection<Transactionlog> Transactionlog { get; set; }
    }
}