// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Transactionlog
    {
        public int Tlid { get; set; }
        public int? Uid { get; set; }
        public int? Seid { get; set; }
        public int? Sharenumber { get; set; }

        public virtual Stocks Se { get; set; }
        public virtual DepotStocks SharenumberNavigation { get; set; }
        public virtual Users UidNavigation { get; set; }
    }
}