// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinanceTrackerLibrary.Models
{
    public partial class Users
    {
        public Users()
        {
            Account = new HashSet<Account>();
            Depot = new HashSet<Depot>();
            Transactionlog = new HashSet<Transactionlog>();
        }

        public int Uid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Depot> Depot { get; set; }
        public virtual ICollection<Transactionlog> Transactionlog { get; set; }
    }
}